### PR TITLE
Sign in

### PR DESCRIPTION
**Pull request by rjackson21**
# Summary
This PR adds styling to the sign in page. `application.erb.html` was edited to allow us to forego the navbar when on the devise views. 

# Trello card
https://trello.com/b/Rbc26zGb/geegcommerce

# Follow ups
Implementing javascript to do some work on the form placeholders to further clone the Aritzia website would be a great idea. Also the background color varies throughout the Aritzia website, ours does not. 

Screen Shot 2022-05-18 at 9 04 05 PM
t

### CODE REVIEW

**Review by dylanerichards — CHANGES_REQUESTED** [review]
Hey Regina, looking great so far! Just have a few suggestions before this is ready to merge:
- Center `SIGN IN OR CREATE AN ACCOUNT TO UNLOCK` text underneath the Aritzia logo
- Add blue facebook logo icon to sign in button
- Add box shadow to facebook login and sign in buttons: https://tobiasahlin.com/blog/how-to-animate-box-shadow/
-

**Comment by rjackson21** [comment]
Hey Dylan, appreciate the suggestions. 

The following changes have been made:

- The centering with 'SIGN IN OR CREATE AN ACCOUNT TO UNLOCK' has been evened out is respect to the Aritzia logo above it
- The blue facebook logo icon has been added to the 'continue with facebook' button 
- Added some shadow effects to the 'continue with facebook' button on the hover using some CSS, the link provided was very helpful

**Review by dylanerichards — CHANGES_REQUESTED** [review]
Great work, again! But I have to request more changes:

- The box shadow around the Facebook button on hover is too big. It needs to be more subtle.
- Additionally, the box shadow does not transition in. It needs to enter and leave smoothly.
- The black sign-in button also needs the same box shadow on hover
- The black sign-in button also needs to change colors slightly on hover

**Comment by rjackson21** [comment]
Hey Dylan, 

I made the changes requested. I switched from writing my own css classes for the hover effects and instead used tailwind classes. I also implemented the 'ease-in-out' class which stopped the the hover effects from being rather harsh. The 'sign in' button has also been imposed with the same tailwind classes, but with that button I included a change in opacity on the hover. Hope this satisfies all requirements!

**Review by dylanerichards — APPROVED** [review]
LGTM!

**Pull request merged**
